spring.application.name=BootData_JPA_TransactionManagement


#===========================cfgs to Mysql=========================
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.url=jdbc:mysql://localhost:3306/BankAccountSBI
#spring.datasource.username=root
#spring.datasource.password=root

#====H2 data base=======
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.url=jdbc:h2:mem:test
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true
#========JPA hibernate properties=====================
#spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true